version: 2
jobs:
  setup:
    working_directory: ~/lucina
    docker:
      - image: circleci/python:3.7-stretch
    steps:
      - checkout
      - restore_cache:
          key: venv-cache-{{ checksum "setup.py" }}
      - run:
          command: |
            python3 -m venv ~/.venv
            . ~/.venv/bin/activate
            pip install -e .[dev]
      - save_cache:
          key: venv-cache-{{ checksum "setup.py" }}
          paths:
            - ~/.venv/

  lint:
    working_directory: ~/lucina
    docker:
      - image: circleci/python:3.7-stretch
    steps:
      - checkout
      - restore_cache:
          key: venv-cache-{{ checksum "setup.py" }}
      - run:
          command: |
            . ~/.venv/bin/activate
            flake8
      - run:
          command: |
            . ~/.venv/bin/activate
            isort -c --diff .

  tests:
    working_directory: ~/lucina
    docker:
      - image: circleci/python:3.7-stretch
    steps:
      - checkout
      - restore_cache:
          key: venv-cache-{{ checksum "setup.py" }}
      - run:
          name: "Run tests"
          command: |
            . ~/.venv/bin/activate
            pytest

workflows:
  version: 2
  tests:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - tests:
          requires:
            - setup
